version: '3.6'

services:

  back-web:
    container_name: zpk_back_web
    build:
      context: ./backend
    command: bash -c "flask run --host=0.0.0.0 --port=5000"
    volumes:
      - ./backend:/usr/src/zpk
    env_file:
      - ./backend/.env
    expose:
      - 5000

  front-web:
    container_name: zpk_front_web
    command: npm start
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/zpk
    expose:
      - 3000

  nginx:
    container_name: zpk_nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - front-web
      - back-web
